# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Csvops < Formula
  desc "Modular CLI toolkit for working with CSV files"
  homepage "https://github.com/maherelgamil/csvops"
  version "0.2.1"

  on_macos do
    on_intel do
      url "https://github.com/maherelgamil/csvops/releases/download/v0.2.1/csvops_0.2.1_darwin_amd64.tar.gz"
      sha256 "8e3ab5cb20ee3487bb7d4e7b2667879fc8685cfdc64d91c61e48b166f0923e11"

      def install
        bin.install "csvops"
      end
    end
    on_arm do
      url "https://github.com/maherelgamil/csvops/releases/download/v0.2.1/csvops_0.2.1_darwin_arm64.tar.gz"
      sha256 "ee99e66b870745d33c00edc35f2bc773e93aaff961a6d5eaaada4ab04ef920d0"

      def install
        bin.install "csvops"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/maherelgamil/csvops/releases/download/v0.2.1/csvops_0.2.1_linux_amd64.tar.gz"
        sha256 "49574ef8943a0b75c8f32993722213a1b66dd39e80c83aa3272790bf2b23c38b"

        def install
          bin.install "csvops"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/maherelgamil/csvops/releases/download/v0.2.1/csvops_0.2.1_linux_arm64.tar.gz"
        sha256 "b5ef21c814a96ff3ec38cfd11614e0541f17c6d4b7b5bee83ccf222430cd7cff"

        def install
          bin.install "csvops"
        end
      end
    end
  end

  test do
    system "#{bin}/csvops", "--version"
  end
end
