# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Csvops < Formula
  desc "Modular CLI toolkit for working with CSV files"
  homepage "https://github.com/maherelgamil/csvops"
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://github.com/maherelgamil/csvops/releases/download/v0.1.2/csvops_0.1.2_darwin_amd64.tar.gz"
      sha256 "c3795665c2652d709905318a53200fb78a444cc02b94fc3b8b286caf357edcdf"

      def install
        bin.install "csvops"
      end
    end
    on_arm do
      url "https://github.com/maherelgamil/csvops/releases/download/v0.1.2/csvops_0.1.2_darwin_arm64.tar.gz"
      sha256 "405561e38a635da0ff9f8a6c9b612e3bccba4b46545b76567443e99ef27e3a46"

      def install
        bin.install "csvops"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/maherelgamil/csvops/releases/download/v0.1.2/csvops_0.1.2_linux_amd64.tar.gz"
        sha256 "04ff6b460ef391120ff249db855ebb98b05ab55553848b9595295f000ef50e05"

        def install
          bin.install "csvops"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/maherelgamil/csvops/releases/download/v0.1.2/csvops_0.1.2_linux_arm64.tar.gz"
        sha256 "c5d687d3c9c6d73db7c28db08e6bd72a696c5bc88effc23cde9ff8715e977f09"

        def install
          bin.install "csvops"
        end
      end
    end
  end

  test do
    system "#{bin}/csvops", "--version"
  end
end
